const examples = [
  {
    name: 'Two Sum',
    prompt: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
    tags: ['math', 'algo'],
    difficulty: 'easy',
    upvotes: 5,
    downvotes: 2,
    rating: 3.5,
    ratings_count: 16,
    timestamp: '2022-5-6',
    author: 'leetcode',
  },
  {
    name: 'Rotate Image',
    prompt: 'You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).',
    tags: ['matrix'],
    difficulty: 'medium',
    upvotes: 9,
    downvotes: 7,
    rating: 5,
    ratings_count: 16,
    timestamp: '2022-5-6',
    author: 'leetcode',
  },
  {
    name: 'Add Two Numbers',
    prompt: 'Given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list \n\nYou may assume the two numbers do not contain any leading zero, except the number 0 itself.',
    examples: [
      { input: 'l1 = [0], l2 = [0]', output: '[0]' },
      { input: 'l1 = [2,4,3], l2 = [5,6,4]', output: '[7,0,8]' },
      { input: 'l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]', output: '[8,9,9,9,0,0,0,1]' },
    ],
    constraints: ['The number of nodes in each linked list is in the range [1, 100]', '0 <= Node.val <= 9', 'It is guaranteed that the list represents a number that does not have leading zeros'],
    tags: ['linked-list', 'math'],
    difficulty: 'medium',
    reported_count: 3,
    rating: 4.8,
    ratings_count: 16,
    timestamp: '2022-5-7',
    author: 'leetcode',
  },
  {
    name: 'Trapping Rain Water',
    prompt: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
    tags: ['story', 'array'],
    difficulty: 'hard',
    upvotes: 9,
    downvotes: 7,
    rating: 4.5,
    ratings_count: 16,
    timestamp: '2022-5-6',
    author: 'leetcode',
  },
  {
    name: 'Trapping Rain Water',
    prompt: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
    tags: ['story', 'array'],
    difficulty: 'hard',
    upvotes: 9,
    downvotes: 7,
    rating: 4.5,
    timestamp: '2022-5-6',
    author: 'leetcode',
  },
  {
    name: 'Trapping Rain Water',
    prompt: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
    tags: ['story', 'array'],
    difficulty: 'hard',
    upvotes: 9,
    downvotes: 7,
    rating: 4.5,
    timestamp: '2022-5-6',
    author: 'leetcode',
  },
];

module.exports = examples;
