const examples = [
  {
    name: 'Two Sum',
    prompt: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\n\nYou can return the answer in any order.',
    tags: ['math', 'algo'],
    examples: [ // TODO: each example object should occupy a code block (```)
      { input: 'nums = [2,7,11,15], target = 9', output: '[0, 1]' },
      { input: 'nums = [3,2,4], target = 6', output: '[1,2]' },
      { input: 'nums = [3,3], target = 6', output: '[0,1]' },
    ],
    constraints: ['`2 <= nums.length <= 10^4`', '`-10^9 <= nums[i] <= 10^9`', '`-10^9 <= target <= 10^9`', '*Only one valid answer exists*'],
    difficulty: 'easy',
    reported_count: 2,
    rating: 3.5,
    ratings_count: 16,
    timestamp: '2022-5-6',
    author: 'leetcode',
  },
  {
    name: 'Rotate Image',
    prompt: 'You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).\n\nYou have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.',
    tags: ['matrix'],
    examples: [
      { input: 'matrix = [[1,2,3],[4,5,6],[7,8,9]]', output: '[[7,4,1],[8,5,2],[9,6,3]]' },
      { input: 'matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]', output: '[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]' },
      { input: '', output: '' },
    ],
    constraints: ['n == matrix.length == matrix[i].length', '1 <= n <= 20', '-1000 <= matrix[i][j] <= 1000'],
    difficulty: 'medium',
    reported_count: 3,
    rating: 5,
    ratings_count: 16,
    timestamp: '2022-5-6',
    author: 'leetcode',
  },
  {
    name: 'Add Two Numbers',
    prompt: 'Given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list \n\nYou may assume the two numbers do not contain any leading zero, except the number 0 itself.',
    examples: [
      { input: 'l1 = [0], l2 = [0]', output: '[0]' },
      { input: 'l1 = [2,4,3], l2 = [5,6,4]', output: '[7,0,8]' },
      { input: 'l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]', output: '[8,9,9,9,0,0,0,1]' },
    ],
    constraints: ['The number of nodes in each linked list is in the range [1, 100]', '0 <= Node.val <= 9', 'It is guaranteed that the list represents a number that does not have leading zeros'],
    tags: ['linked list', 'math'],
    difficulty: 'medium',
    reported_count: 3,
    rating: 4.8,
    ratings_count: 16,
    timestamp: '2022-5-7',
    author: 'leetcode',
  },
  {
    name: 'Trapping Rain Water',
    prompt: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
    examples: [
      { input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' },
      { input: 'height = [4,2,0,3,2,5]', output: '9' },
      { input: '', output: '' },
    ],
    constraints: ['n == height.length', '1 <= n <= 2 * 10^4', '0 <= height[i] <= 10^5'],
    tags: ['story', 'array'],
    difficulty: 'hard',
    reported_count: 2,
    rating: 4.5,
    ratings_count: 16,
    timestamp: '2022-5-6',
    author: 'leetcode',
  },
  {
    name: 'Climbing Stairs',
    prompt: 'You are climbing a staircase. It takes n steps to reach the top.\n\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?',
    examples: [
      { input: 'n = 2', output: '2' },
      { input: 'n = 3', output: '3' },
      { input: '', output: '' },
    ],
    constraints: ['1 <= n <= 45'],
    tags: ['story', 'combo'],
    difficulty: 'easy',
    reported_count: 0,
    rating: 2.7,
    ratings_count: 16,
    timestamp: '2022-5-7',
    author: 'leetcode',
  },
  {
    name: 'First Missing Positive',
    prompt: 'Given an unsorted integer array nums, return the smallest missing positive integer.\n\nYou must implement an algorithm that runs in O(n) time and uses constant extra space.',
    examples: [
      { input: 'nums = [1,2,0]', output: '3' },
      { input: 'nums = [3,4,-1,1]', output: '2' },
      { input: 'nums = [7,8,9,11,12]', output: '1' },
    ],
    constraints: ['1 <= nums.length <= 5 * 10^5', '-2^31 <= nums[i] <= 2^31 - 1'],
    tags: ['array', 'numbers'],
    difficulty: 'hard',
    reported_count: 4,
    rating: 4.1,
    ratings_count: 34,
    timestamp: '2022-5-7',
    author: 'leetcode',
  },
  {
    name: 'Validate Binary Search Tree',
    prompt: 'Given the root of a binary tree, determine if it is a valid binary search tree (BST).\n\nA valid BST is defined as follows:\n\n-The left subtree of a node contains only nodes with keys less than the node\'s key.\n-The right subtree of a node contains only nodes with keys greater than the node\'s key.\nBoth the left and right subtrees must also be binary search trees.',
    examples: [
      { input: 'root = [2,1,3]', output: 'true' },
      { input: 'root = [5,1,4,null,null,3,6]', output: 'false' },
    ],
    constraints: ['The number of nodes in the tree is in the range [1, 10^4]', '-2^31 <= Node.val <= 2^31 - 1'],
    tags: ['binary tree'],
    difficulty: 'medium',
    reported_count: 7,
    rating: 4.6,
    ratings_count: 20,
    timestamp: '2022-5-7',
    author: 'leetcode',
  },
  {
    name: 'Group Anagrams',
    prompt: 'Given an array of strings strs, group the anagrams together. You can return the answer in any order.\n\nAn Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.',
    examples: [
      { input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' },
      { input: 'strs = [""]', output: '[[""]]' },
      { input: 'strs = ["a"]', output: '[["a"]]' },
    ],
    constraints: ['1 <= strs.length <= 10^4', '0 <= strs[i].length <= 100', 'strs[i] consists of lowercase English letters'],
    tags: ['words', 'array'],
    difficulty: 'medium',
    reported_count: 5,
    rating: 2.7,
    ratings_count: 50,
    timestamp: '2022-5-7',
    author: 'leetcode',
  },
];

// {
//   name: '',
//   prompt: '',
//   examples: [
//     { input: '', output: '' },
//     { input: '', output: '' },
//     { input: '', output: '' },
//   ],
//   constraints: ['', '', ''],
//   tags: ['', ''],
//   difficulty: '',
//   reported_count: 0,
//   rating: 0,
//   ratings_count: 0,
//   timestamp: '',
//   author: '',
// },

module.exports = examples;
